# Generated by Django 5.0.3 on 2024-04-28 17:35

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('category', models.TextField(validators=[django.core.validators.MaxLengthValidator(50)])),
            ],
            options={
                'db_table': '"app_data"."products"',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(validators=[django.core.validators.MaxLengthValidator(400)])),
                ('discount_amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 4, 28))])),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"app_data"."promotions"',
            },
        ),
        migrations.CreateModel(
            name='ProductToPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.promotion')),
            ],
            options={
                'db_table': '"app_data"."product_to_promotion"',
                'unique_together': {('product', 'promotion')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(through='polls.ProductToPromotion', to='polls.promotion'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(400)])),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
            ],
            options={
                'db_table': '"app_data"."reviews"',
            },
        ),
    ]
